# Generated by Django 4.2.28 on 2026-02-28 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preview', models.ImageField(upload_to='cartoons/gifs/')),
                ('frames_data', models.JSONField(blank=True, default=dict)),
                ('fps', models.PositiveSmallIntegerField(default=12)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
