# Generated by Django 4.2.28 on 2026-03-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
