# Generated by Django 4.2.28 on 2026-03-09 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartoons', '0003_emailverificationtoken_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='author',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cartoons', to=settings.AUTH_USER_MODEL),
        ),
    ]
