# Generated by Django 4.2.28 on 2026-03-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0004_alter_cartoon_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='draw_history',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
