# Generated by Django 4.2.28 on 2026-03-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0005_cartoon_draw_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartoon',
            name='draw_history',
        ),
    ]
