# Generated by Django 4.2.28 on 2026-03-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0006_remove_cartoon_draw_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cartoon',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Теги'),
        ),
    ]
