# Generated by Django 4.2.28 on 2026-04-30 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartoons', '0007_cartoon_description_cartoon_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cartoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cartoons.cartoon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_sort', models.CharField(choices=[('popular', 'По популярности'), ('newest', 'По новизне')], default='popular', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cartoons.comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartoonLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cartoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cartoons.cartoon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('comment', 'user'), name='unique_comment_user_like'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__gt', '')), fields=('comment', 'session_key'), name='unique_comment_session_like'),
        ),
        migrations.AddConstraint(
            model_name='cartoonlike',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('cartoon', 'user'), name='unique_cartoon_user_like'),
        ),
        migrations.AddConstraint(
            model_name='cartoonlike',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__gt', '')), fields=('cartoon', 'session_key'), name='unique_cartoon_session_like'),
        ),
    ]
