# Generated by Django 4.2.28 on 2026-04-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0009_usernote_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
