# Generated by Django 4.2.28 on 2026-04-30 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0011_add_cartoon_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_avatar', to='cartoons.cartoon'),
        ),
    ]
