# Generated by Django 4.2.28 on 2026-05-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0016_comment_parent_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='rec_sort',
            field=models.CharField(default='trending', max_length=20),
        ),
    ]
