# Generated by Django 4.2.28 on 2026-05-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0017_comment_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
