# Generated by Django 4.2.28 on 2026-05-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0018_comment_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
