# Generated by Django 4.2.28 on 2026-05-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0019_alter_cartoon_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='index_sort',
            field=models.CharField(default='trending', max_length=20),
        ),
    ]
