# Generated by Django 5.2.17 on 2026-09-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0024_comment_popular_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
    ]
