# Generated by Django 5.2.17 on 2026-09-13 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0025_alter_cartoon_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartoonlike',
            name='unique_cartoon_session_like',
        ),
        migrations.RemoveConstraint(
            model_name='commentlike',
            name='unique_comment_session_like',
        ),
        migrations.RemoveField(
            model_name='cartoonlike',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='session_key',
        ),
    ]
