# Generated by Django 5.2.17 on 2026-09-16 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0027_comment_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплён на странице автора'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='is_troll',
            field=models.BooleanField(default=False, help_text='Комментарии показываются с кнопкой "заблокировать" всем, а не только автору мульта.', verbose_name='Тролль'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='profile_slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
