# Generated by Django 5.2.17 on 2026-09-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0029_backfill_profile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('default_avatar_gif', models.ImageField(
                    blank=True, null=True, upload_to='avatars/',
                    verbose_name='Аватар по умолчанию')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
