# Generated by Django 5.2.17 on 2026-09-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0030_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='profile_slug',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='display_name',
            field=models.CharField(
                blank=True, default='', max_length=15,
                verbose_name='Отображаемое имя'),
        ),
    ]
