# Generated by Django 5.2.17 on 2026-09-18 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0031_remove_userpreference_profile_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccessLog',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(
                    verbose_name='IP-адрес')),
                ('device_id', models.CharField(
                    blank=True, default='', max_length=36)),
                ('user_agent', models.CharField(
                    blank=True, default='', max_length=255)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='access_logs',
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись о входе',
                'verbose_name_plural': 'Записи о входах (IP/устройства)',
                'unique_together': {('user', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='BannedIdentifier',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('kind', models.CharField(
                    choices=[
                        ('ip', 'IP-адрес'),
                        ('device', 'Device ID (cookie)')],
                    max_length=10)),
                ('value', models.CharField(
                    max_length=100, verbose_name='Значение')),
                ('reason', models.CharField(
                    blank=True, max_length=255, verbose_name='Причина')),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бан по IP/устройству',
                'verbose_name_plural': 'Баны по IP/устройствам',
                'unique_together': {('kind', 'value')},
            },
        ),
    ]
