# Generated by Django 5.2.17 on 2026-09-18 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0032_accountaccesslog_bannedidentifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='continuation_of',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='continuations', to='cartoons.cartoon',
                verbose_name='Оригинал'),
        ),
    ]
