# Generated by Django 5.2.17 on 2026-09-18 12:34

import cartoons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0033_cartoon_continuation_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='tags',
            field=models.JSONField(
                blank=True, default=list,
                encoder=cartoons.models.UnicodeJSONEncoder,
                verbose_name='Теги'),
        ),
    ]
