# Generated by Django 5.2.17 on 2026-09-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0035_reencode_cartoon_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='search_tag_mode',
            field=models.CharField(
                choices=[('and', 'И'), ('or', 'ИЛИ')], default='and',
                max_length=3,
                verbose_name='Режим сочетания тегов в поиске'),
        ),
    ]
